spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://ec2-34-231-221-151.compute-1.amazonaws.com:5432/dcf2caar0m3jq9
        username: gvanouwiwwkhls
        password: c374bb9d0d31ba2fe058ecbc356a1411d4ebcfe4c8435967b5d1e3a3a0715458
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        schema: classpath:/schema-postgresql.sql

 

    jpa: 
        hibernate:
            ddl-auto: create-drop
